### ISSUE TITLE
keeps getting roll_back

### ISSUE THREAD

**Issue by neonix888** [awslabs/cloudwatch-logs-subscription-consumer#13]
I don't know if any has try this but I kept getting roll_back failures. Also the roll_back eventually failed due to dependencies.

**Comment by dvassallo** [comment]
You may want to check out issue #1 to see if your stack is also failing to start because it cannot find the CloudWatch Logs log group.

Note that to see the cfn-init log you would need to set the "Rollback on Failure" option to "No" while setting up the CloudFormation stack. 

![No Rollback on Failure](https://cloud.githubusercontent.com/assets/137916/9614707/3cad19fe-50a8-11e5-9fe5-5b0896360bff.png)

Then you would be able to ssh to any one of your EC2 instances using the key pair you chose when setting up the CloudFormation stack:

```
chmod 400 <your-key>.pem
ssh -i "<your-key>.pem" ec2-user@<ec2-public-ip>
```

From the EC2 instance you may want to check the following log files for any errors:
- /var/log/cfn-init-cmd.log
- /var/log/cloud-init.log

**Comment by neonix888** [comment]
Thank you @DVassallo
