### ISSUE TITLE
Cloudformation doesn't start sample template

### ISSUE THREAD

**Issue by RyuJungDae** [awslabs/cloudwatch-logs-subscription-consumer#4]
Hi, I am aws begginer operator

I want kinesis, elasticsearch and kibana 
So google search and this sample discover.
I want Earnestly this sample(Cloudformation) start.
But, sample template for make Cloudformation, error issue.

===============================================================================

19:12:55 UTC+0900	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	fff	The following resource(s) failed to create: [WaitCondition]. . Rollback requested by user.
19:12:53 UTC+0900	CREATE_FAILED	AWS::CloudFormation::WaitCondition	WaitCondition	WaitCondition received failed message: 'failed to run cfn-init' for uniqueId: i-c227a060
Physical ID:arn:aws:cloudformation:ap-northeast-1:432113265161:stack/fff/f9925e20-5090-11e5-911f-5001aba75438/WaitHandle
19:09:45 UTC+0900	CREATE_COMPLETE	AWS::AutoScaling::AutoScalingGroup	ElasticsearchServerGroup	
19:07:57 UTC+0900	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	ElasticsearchServerGroup	Resource creation Initiated
19:07:56 UTC+0900	CREATE_IN_PROGRESS	AWS::CloudFormation::WaitCondition	WaitCondition	Resource creation Initiated

===============================================================================

Please, help me

**Comment by DVassallo** [comment]
Hello @RyuJungDae - You may want to check out issue #1 to see if your stack is also failing to start because it cannot find the CloudWatch Logs log group.

Note that to see the cfn-init log you would need to set the "Rollback on Failure" option to "No" while setting up the CloudFormation stack. 

![No Rollback on Failure](https://cloud.githubusercontent.com/assets/137916/9614707/3cad19fe-50a8-11e5-9fe5-5b0896360bff.png)

Then you would be able to ssh to any one of your EC2 instances using the key pair you chose when setting up the CloudFormation stack:

```
chmod 400 <your-key>.pem
ssh -i "<your-key>.pem" ec2-user@<ec2-public-ip>
```

From the EC2 instance you may want to check the following log files for any errors:

* /var/log/cfn-init-cmd.log
* /var/log/cloud-init.log

**Comment by RyuJungDae** [comment]
Thank you very much~.
I fixed issue.
